services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.cloud.jacobmiller22.com"
      SIGNUPS_ALLOWED: "true"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 7277:80
    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: true
