services:
  restreamer:
    container_name: restreamer
    image: datarhei/restreamer:latest
    networks:
      - nginx-proxy-manager
    volumes:
      - ./data/restreamer/config:/core/config
      - ./data/restreamer/data:/core/data
    privileged: true
    devices:
      - /dev/video0:/dev/video0
networks:
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: true
