services:
  motion:
    container_name: motion
    build:
      context: .
    networks:
      - nginx-proxy-manager
    volumes:
      - ./data/motion/motion.conf:/etc/motion/motion.conf
    privileged: true
    devices:
      - /dev/video0:/dev/video0
networks:
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: true
